VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "uuid" do |uuid|
	  uuid.vm.box = "ubuntu/precise64"
	  uuid.vm.hostname = "uuid.dev"
	  uuid.vm.provision :shell, path: "uuid-bootstrap.sh"
	  uuid.vm.network :private_network, ip:"192.168.48.48"
	  uuid.vm.network :forwarded_port, host: 8094, guest: 8094
	  uuid.vm.synced_folder "../", "/vagrant/uuid"
	  uuid.vm.provider "virtualbox" do |v|
	  	v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--memory", "512"]
      end
  end
end